### ISSUE TITLE
Upgrading to latest version, having issue with allure-js-commons dependency

### ISSUE THREAD

**Issue by Guzikowski** [allure-framework/allure-js#1151]
Upgrading from 2.15.1 to 3.0.1, when building there are 2 errors from allure-js-commons when using 

The `\node_modules\allure-js-commons\dist\types\sdk\reporter\utils.d.ts` has a reference to 

```ts
/// <reference path="../../../../src/types/properties.d.ts" /> 
```

First the path does not exist, and the file does not exist. 

There were 2 errors based on this configuration and it required to add paths to files

```
{
  "compilerOptions": {
...
    "target": "es2022",
    "moduleResolution": "node",
    "lib": ["es2022", "dom"],
    "module": "ESNext",
....
    "paths": {
      "allure-js-commons/sdk/reporter": [
        "../node_modules/allure-js-commons/dist/types/sdk/reporter/index.d.ts"
      ],
      "allure-js-commons/src/types/properties": [
        "../node_modules/allure-js-commons/dist/types/properties.d.ts"
      ]
    }
  },
}
```

**To Reproduce**
1.Adjust tsconfig without paths
2. npm install using v3
3. Should get 2 errors
4. Add paths
5. recompile
6. Should get 1 error

**Expected behavior**
Should compile without errors. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version latest

**Additional context**
Currently, the compile options are needed for other packages so unable to adjust for this. 

The fix which is a bit of a hack
Add File
```
node_modules\allure-js-commons\dist\types\properties.d.ts
```

Contents
```
// types/properties.d.ts
declare module 'properties' {
  const properties: any;
  export default properties;
}
```

Edit File
```
node_modules\allure-js-commons\dist\types\sdk\reporter\utils.d.ts
```

Change
```
/// <reference path="../../../types/properties.d.ts" />
```

**Comment by joefassbender** [comment]
This also appears to be happening in versions 3.0.2 and 3.0.3.

**Comment by Guzikowski** [comment]
Spent another hour on this to see if anything progressed. 

I found yet another hack which would not be supported for us going forward.

You can create your own properties.d.ts and have that be compiled in, which does work. But the 

The \node_modules\allure-js-commons\dist\types\sdk\reporter\utils.d.ts reference to

/// <reference path="../../../../src/types/properties.d.ts" /> would need to be removed or commented. 

Ideally, we should not need to do this.

I originally was using the 
import { allure } from 'allure-playwright';

which is being deprecated to use the recommended 
import { label } from 'allure-js-commons';

Originally, v2.15 was working, but now moving to directly call allure-js-common there is issues.

**Comment by delatrie** [comment]
Hi, everyone. We're investigating the cause and will fix the issue soon.

**Comment by Guzikowski** [comment]
I attempted to create an override file

`// src/types/custom-allure-js-commons-utils.d.ts
declare module 'allure-js-commons/sdk/reporter/utils' {
  /// <reference path="./properties.d.ts" />
  export * from 'allure-js-commons/dist/types/sdk/reporter/utils';
}
`
With changes to my tsconfig and creating a properties file internal to my source. Sadly the original 

`/// <reference path="../../../../src/types/properties.d.ts" /> `

still took precedence...

Commenting that line or editing the above line to point to my file does work, but again not maintainable solution. 

Thanks again for looking into a fix. I assume adding properties to the dist and adjusting the ref might do the trick.

**Comment by delatrie** [comment]
@joefassbender , @Guzikowski the issue should be fixed in 3.0.4. Could you please verify that?

**Comment by Guzikowski** [comment]
@delatrie Your fix has helped me complete my migration. But, I still needed to add a fix for the upgrade. 

On a fresh clean migration branch, I get this error

node_modules/allure-playwright/dist/types/model.d.ts:1:37 - error TS2307: Cannot find module 'allure-js-commons/sdk/reporter' or its corresponding type declarations. There are types at '... /node_modules/allure-js-commons/dist/types/sdk/reporter/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

1 import type { ReporterConfig } from "allure-js-commons/sdk/reporter";

The workaround is to add a file with the content:

declare module 'allure-js-commons/sdk/reporter' {
  export * from 'allure-js-commons/dist/types/sdk/reporter/index';
}

Since I can manage this, I think it is low priority to fix, but might be something to fix for other users not knowing the fix. 

Much appreciated on the original issue.

**Comment by joefassbender** [comment]
Our team is still experiencing this  while running`npx tsc --noEmit`, so it is failing our pre-merge type check.

**Comment by Guzikowski** [comment]
@joefassbender Are you seeing the original issue with properties? Or are you seeing the issue I noted in my last post? The work around I implemented might be temporary fix for you. My solution is working in my local and Github pipeline. You might need to confirm the issue you are facing.

**Comment by joefassbender** [comment]
@Guzikowski apologies, I'm seeing the issue from your last post [here](https://github.com/allure-framework/allure-js/issues/1151#issuecomment-2389505238). 

We could implement a workaround, but we would expect this to work out of the box. @delatrie please advise if a separate issue should be recorded.

**Comment by delatrie** [comment]
@joefassbender @Guzikowski What version of Node.js you target and what `moduleResolution` you use?

**Comment by joefassbender** [comment]
The node version is `20.10.0`. and ` "moduleResolution":"node"`.

**Comment by delatrie** [comment]
From [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node):
> --moduleResolution node was renamed to node10 (keeping node as an alias for backward compatibility) in TypeScript 5.0. It reflects the CommonJS module resolution algorithm as it existed in Node.js versions earlier than v12. **It should no longer be used.**

Do you have any reason not to use [`"node16"` or `"nodenext"`](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext-1) as they recommend for the Node.js version you target?

> These modes reflect the module resolution behavior of Node.js v12 and later.

**Comment by Guzikowski** [comment]
My node version is v21.6.2 and moduleResolution is node. It is not the Playwright project that drives these settings, I have several internal NPM packages that are dependent to be used in Cypress and Artillery, which do not always play nice in native language standards. 

I would need to review if this is still a dependency, but I understand that my scenario might be a niche issue that my work around is temporary until the other test frameworks catch up to the latest standards.

**Comment by joefassbender** [comment]
@delatrie we were able to resolve on our side. Thanks for all the help.
