### ISSUE TITLE
[allure-jest] Add API to write environment info

### ISSUE THREAD

**Issue by maks-rafalko** [allure-framework/allure-js#979]
**Is your feature request related to a problem? Please describe.**

Currently, it's impossible to add environment information, displayed on the main page of Allure report: https://allurereport.org/docs/jest/#environment-information

**Describe the solution you'd like**

I would like to make it working out of the box in allure-jest reporter, for example adding this information in Jest configuration (https://allurereport.org/docs/jest-configuration/#allure-jest-configuration) or just by calling some public method on `global.allure`

**Describe alternatives you've considered**
-

**Additional context**
Currently, there is a method `writeEnvironmentInfo()` on `AllureRuntime` interface, but this is an internal thing which is not available for public usage in allure-jest.

**Comment by baev** [comment]
fixed in #1021

**Comment by maks-rafalko** [comment]
Though it would be nice to have `.writeEnvironmentInfo({...})` public API for Jest, as currently we write there dynamic data, not only data from jest config

**Comment by maks-rafalko** [comment]
up

We are upgrading to v3 and we still can't dynamically write environment info. Please consider to somehow allow providing dynamic values.

Our use case - we test N microservices and get their versions by calling external URls, so our retrieval logic is async. We can't write these values inside `jest.config.ts` as static values.
